import type { Metadata } from "next";
import { RainbowProvider } from "@/providers/rainbow-provider";
import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RainbowProvider>
          {children}
        </RainbowProvider>
      </body>
    </html>
  );
}
