
import { OpenAPI } from './core/OpenAPI';

// 自动配置API基础URL
OpenAPI.BASE = process.env.NEXT_PUBLIC_NEST_URL || '';
OpenAPI.WITH_CREDENTIALS = true;
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AbortUploadDto } from './models/AbortUploadDto';
export type { AuthErrorResponseDto } from './models/AuthErrorResponseDto';
export type { CategoryListResponseDto } from './models/CategoryListResponseDto';
export type { CategoryResponseDto } from './models/CategoryResponseDto';
export type { CompleteUploadDto } from './models/CompleteUploadDto';
export type { CourseListResponseDto } from './models/CourseListResponseDto';
export type { CourseResponseDto } from './models/CourseResponseDto';
export type { CreateCategoryDto } from './models/CreateCategoryDto';
export type { CreateCourseDto } from './models/CreateCourseDto';
export type { CreateCourseSectionDto } from './models/CreateCourseSectionDto';
export type { CreatePermissionDto } from './models/CreatePermissionDto';
export type { CreateRoleDto } from './models/CreateRoleDto';
export type { CreateUserDto } from './models/CreateUserDto';
export type { ListPartsDto } from './models/ListPartsDto';
export type { LogoutResponseDto } from './models/LogoutResponseDto';
export type { NonceResponseDto } from './models/NonceResponseDto';
export type { PartDetail } from './models/PartDetail';
export type { PermissionInfo } from './models/PermissionInfo';
export type { PermissionListResponseDto } from './models/PermissionListResponseDto';
export type { PermissionResponseDto } from './models/PermissionResponseDto';
export type { QueryCategoryDto } from './models/QueryCategoryDto';
export type { QueryCategoryWithoutPaginationDto } from './models/QueryCategoryWithoutPaginationDto';
export type { QueryCourseDto } from './models/QueryCourseDto';
export type { QueryPermissionDto } from './models/QueryPermissionDto';
export type { QueryRoleDto } from './models/QueryRoleDto';
export type { QueryUserDto } from './models/QueryUserDto';
export type { ResponseModel } from './models/ResponseModel';
export type { RoleListResponseDto } from './models/RoleListResponseDto';
export type { RoleResponseDto } from './models/RoleResponseDto';
export type { SessionResponseDto } from './models/SessionResponseDto';
export type { SignatureErrorResponseDto } from './models/SignatureErrorResponseDto';
export type { UpdateCategoryDto } from './models/UpdateCategoryDto';
export type { UpdateCourseDto } from './models/UpdateCourseDto';
export type { UpdateCourseSectionDto } from './models/UpdateCourseSectionDto';
export type { UpdatePermissionDto } from './models/UpdatePermissionDto';
export type { UpdateRoleDto } from './models/UpdateRoleDto';
export type { UpdateUserDto } from './models/UpdateUserDto';
export type { UpdateUserRolesDto } from './models/UpdateUserRolesDto';
export type { UploadFileDto } from './models/UploadFileDto';
export type { UserListResponseDto } from './models/UserListResponseDto';
export type { UserResponseDto } from './models/UserResponseDto';
export type { VerifySignatureDto } from './models/VerifySignatureDto';
export type { VideoPartDto } from './models/VideoPartDto';

export { $AbortUploadDto } from './schemas/$AbortUploadDto';
export { $AuthErrorResponseDto } from './schemas/$AuthErrorResponseDto';
export { $CategoryListResponseDto } from './schemas/$CategoryListResponseDto';
export { $CategoryResponseDto } from './schemas/$CategoryResponseDto';
export { $CompleteUploadDto } from './schemas/$CompleteUploadDto';
export { $CourseListResponseDto } from './schemas/$CourseListResponseDto';
export { $CourseResponseDto } from './schemas/$CourseResponseDto';
export { $CreateCategoryDto } from './schemas/$CreateCategoryDto';
export { $CreateCourseDto } from './schemas/$CreateCourseDto';
export { $CreateCourseSectionDto } from './schemas/$CreateCourseSectionDto';
export { $CreatePermissionDto } from './schemas/$CreatePermissionDto';
export { $CreateRoleDto } from './schemas/$CreateRoleDto';
export { $CreateUserDto } from './schemas/$CreateUserDto';
export { $ListPartsDto } from './schemas/$ListPartsDto';
export { $LogoutResponseDto } from './schemas/$LogoutResponseDto';
export { $NonceResponseDto } from './schemas/$NonceResponseDto';
export { $PartDetail } from './schemas/$PartDetail';
export { $PermissionInfo } from './schemas/$PermissionInfo';
export { $PermissionListResponseDto } from './schemas/$PermissionListResponseDto';
export { $PermissionResponseDto } from './schemas/$PermissionResponseDto';
export { $QueryCategoryDto } from './schemas/$QueryCategoryDto';
export { $QueryCategoryWithoutPaginationDto } from './schemas/$QueryCategoryWithoutPaginationDto';
export { $QueryCourseDto } from './schemas/$QueryCourseDto';
export { $QueryPermissionDto } from './schemas/$QueryPermissionDto';
export { $QueryRoleDto } from './schemas/$QueryRoleDto';
export { $QueryUserDto } from './schemas/$QueryUserDto';
export { $ResponseModel } from './schemas/$ResponseModel';
export { $RoleListResponseDto } from './schemas/$RoleListResponseDto';
export { $RoleResponseDto } from './schemas/$RoleResponseDto';
export { $SessionResponseDto } from './schemas/$SessionResponseDto';
export { $SignatureErrorResponseDto } from './schemas/$SignatureErrorResponseDto';
export { $UpdateCategoryDto } from './schemas/$UpdateCategoryDto';
export { $UpdateCourseDto } from './schemas/$UpdateCourseDto';
export { $UpdateCourseSectionDto } from './schemas/$UpdateCourseSectionDto';
export { $UpdatePermissionDto } from './schemas/$UpdatePermissionDto';
export { $UpdateRoleDto } from './schemas/$UpdateRoleDto';
export { $UpdateUserDto } from './schemas/$UpdateUserDto';
export { $UpdateUserRolesDto } from './schemas/$UpdateUserRolesDto';
export { $UploadFileDto } from './schemas/$UploadFileDto';
export { $UserListResponseDto } from './schemas/$UserListResponseDto';
export { $UserResponseDto } from './schemas/$UserResponseDto';
export { $VerifySignatureDto } from './schemas/$VerifySignatureDto';
export { $VideoPartDto } from './schemas/$VideoPartDto';

export { AppService } from './services/AppService';
export { AuthService } from './services/AuthService';
export { CategoryService } from './services/CategoryService';
export { CourseService } from './services/CourseService';
export { PermissionService } from './services/PermissionService';
export { RoleService } from './services/RoleService';
export { UploadService } from './services/UploadService';
export { UsersService } from './services/UsersService';
